- hosts: ome_servers
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Install software-properties-common (Ubuntu/Debian)
      apt:
        name: software-properties-common
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Certbot
      apt:
        name: python3-certbot-nginx
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Generate SSL certificate for live.twoja_domena.com
      shell: |
        certbot --nginx -d live.twoja_domena.com --non-interactive --agree-tos --email admin@twoja_domena.com
      args:
        creates: /etc/letsencrypt/live/live.twoja_domena.com/fullchain.pem
      when: ansible_os_family == 'Debian'

    - name: Ensure /etc/letsencrypt/dhparams directory exists
      file:
        path: /etc/letsencrypt/dhparams
        state: directory
        mode: '0755'
      become: yes

    - name: Generate dhparam.pem (this may take some time)
      command: openssl dhparam -out /etc/letsencrypt/dhparams/dhparam.pem 2048
      args:
        creates: /etc/letsencrypt/dhparams/dhparam.pem
      become: yes

    - name: Copy Nginx configuration for live.twoja_domena.com
      copy:
        src: /app/nginx-http.conf
        dest: /etc/nginx/sites-available/live.twoja_domena.com.conf
        remote_src: yes
      notify: restart nginx

    - name: Disable the default Nginx site
      become: yes
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Enable Nginx configuration
      become: yes
      file:
        src: /etc/nginx/sites-available/live.twoja_domena.com.conf
        dest: /etc/nginx/sites-enabled/live.twoja_domena.com.conf
        state: link

    - name: Set ownership and permissions for /app/player_files/
      file:
        path: /app/player_files/
        owner: "www-data"
        group: "www-data"
        mode: '0755'
        recurse: yes
      become: yes

    - name: Set ownership and permissions for /app/player_files/thumbnails/
      file:
        path: /app/player_files/thumbnails/
        owner: tomek10861
        group: www-data
        mode: '0755'
        recurse: yes
      become: yes

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: false
      ignore_errors: true

    - name: Restart Nginx if configuration is ok
      meta: flush_handlers
      when: nginx_test.rc == 0

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: Run OvenMediaEngine Docker Container
      docker_container:
        name: ovenmediaengine
        image: airensoft/ovenmediaengine:latest
        volumes:
          - "/app/Server.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml"
          - "/etc/letsencrypt/archive/live.twoja_domena.com:/etc/cert-over"
        ports:
          - "1935:1935"
          - "3334:3334"
          - "3478:3478"
        restart_policy: always